name: test release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Retrieve tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::test

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.1

      - name: Create tarballs and zips
        run: ./release.sh test

      - name: Log zip
        run: |
          unzip -l "releases/magic_castle-*.zip"
